---
title: "Formal Models"
author: "Ulrich Lösener"
date: "8 5 2022"
output: html_document
---

This is the code used for model formalisation and data generation for the two competing models.
Note that when a therapeutic intervention is simulated, some lines need to be commented out. 

### Model 1 - the vicious cycle model

Starting values
```{r Starting Values Model 1}
# set number of timepoints to be simulated
# each timepoint represents one day
tpoints <- 360

# storing space and starting value for the binary variable "trigger"
trig <- rep(NA, tpoints) 
trig[1] <- 0

# storing space and starting value for the categorical (0-3) variable "anxiety"
anx <- rep(NA, tpoints) 
anx[1] <- 0

# storing space and starting value for the binary variable "restorative safety behaviours"
rsb <- rep(NA, tpoints) 
rsb[1] <- 0

# storing space and starting value for the categorical (0-3) variable "belief"
bel <- rep(NA, tpoints) 
bel[1] <- 0

# storing space and starting value for the binary variable "preventive safety behaviors"
psb <- rep(NA, tpoints) 
psb[1] <- 0

# storing space for N people
N <- 1000
ppl.long <- matrix(NA, nrow=tpoints*N, ncol=9)
colnames(ppl.long) <- c("ID", "trig", "anx", "rsb", "bel", "psb", "par1", "par2", "tpoints")
```

The model
```{r Data Generation Model 1}
# set seed for reproducibility 
set.seed(123)
# set number of loops for outer for loop
sequ <- seq(from=1, to=(N*tpoints), by=tpoints)

#  outer loop - between person for N people
for (j in sequ){
  # draw latent disease value from beta distribution
  lat <- rbeta(1, 1.3, 6)
  # randomly draw between-person parameters
  par1 <- sample(c(.1, 1), 1, replace=T, prob=c(1-lat, lat))
  ifelse(par1==.1, 
         par2 <- .01,
         par2 <- .09)
  
  # inner loop - within person for t timepoints
  for (i in 2:tpoints){
  # transition matrix of trigger
  p01.trig <- 0.15*(bel[i-1]+1)
  p00.trig <- 1-p01.trig
  p11.trig <- p01.trig
  p10.trig <- p00.trig
  trans.trig <- matrix(c(p00.trig, p01.trig,
                         p10.trig, p11.trig), byrow=T, nrow=2)
  trig[i] <- ifelse(trig[i-1] == 0,                      
                 rbinom(1,1,prob=trans.trig[1,2]),
                 rbinom(1,1,prob=trans.trig[2,2]))
  # transition matrix of anxiety
  p00.anx <- .5/(bel[i-1]+1)
  p01.anx <- .3/(bel[i-1]+1)
  p03.anx <- .2/(bel[i-1]+1)
  p02.anx <- 1-(p00.anx+p01.anx+p03.anx)
  p10.anx <- .3/(bel[i-1]+1)
  p11.anx <- .5/(bel[i-1]+1)
  p13.anx <- .2/(bel[i-1]+1)
  p12.anx <- 1-(p10.anx+p11.anx+p13.anx)
  p20.anx <- .2/(bel[i-1]+1)
  p21.anx <- .3/(bel[i-1]+1)
  p23.anx <- .5/(bel[i-1]+1)
  p22.anx <- 1-(p20.anx+p21.anx+p23.anx)
  p30.anx <- .2/(bel[i-1]+1)
  p31.anx <- .3/(bel[i-1]+1)
  p33.anx <- .5/(bel[i-1]+1)
  p32.anx <- 1-(p30.anx+p31.anx+p33.anx)
  trans.anx <- matrix(c(p00.anx, p01.anx, p02.anx, p03.anx,
                        p10.anx, p11.anx, p12.anx, p13.anx,
                        p20.anx, p21.anx, p22.anx, p23.anx,
                        p30.anx, p31.anx, p32.anx, p33.anx),
                       byrow = T, nrow = 4)  
  anx[i] <- if (trig[i]==0) {0}
             else if (trig[i]==1 & anx[i-1]==0) {
               sample(c(0,1,2,3), 1, prob=c(p00.anx,p01.anx,p02.anx,p03.anx))}
             else if (trig[i]==1 & anx[i-1]==1) {
               sample(c(0,1,2,3), 1, prob=c(p10.anx,p11.anx,p12.anx,p13.anx))}
             else if (trig[i]==1 & anx[i-1]==2) {
               sample(c(0,1,2,3), 1, prob=c(p20.anx,p21.anx,p22.anx,p23.anx))}
             else {
               sample(c(0,1,2,3), 1, prob=c(p30.anx,p31.anx,p32.anx,p33.anx))}
  # transition matrix of restorative safety behaviour (RSB)
  p01.rsb <- -exp(-par1*anx[i])+1
  p00.rsb <- 1-p01.rsb
  p11.rsb <- -exp(-2*par1*anx[i])+1
  p10.rsb <- 1-p11.rsb
  trans.rsb <- matrix(c(p00.rsb, p01.rsb,
                        p10.rsb, p11.rsb), byrow=T, nrow=2)
  rsb[i] <- ifelse(rsb[i-1] == 0,
            rbinom(1,1,prob=trans.rsb[1,2]),
            rbinom(1,1,prob=trans.rsb[2,2]))
  # if therapeutic intervention is simulated, uncomment the following code and comment out the previous 3 lines
 #rsb[i] <- ifelse(i >= 15, 0, ifelse(rsb[i-1] == 0,
           #rbinom(1,1,prob=trans.rsb[1,2]),
           #rbinom(1,1,prob=trans.rsb[2,2])))
  # transition matrix of belief
  p00.bel <- if      (trig[i]==0)                                             {.85}
             else if (trig[i]==1 & rsb[i]==0 & psb[i-1]==0)                   {.9}
             else if ((trig[i]==1 & rsb[i]==1) || (trig[i]==1 & psb[i-1]==1)) {.4} 
             else                                                             {.1}
  p01.bel <- 1 - p00.bel
  p02.bel <- 0
  p03.bel <- 0
  p10.bel <- if      (trig[i]==0)                                             {.1}#
             else if (trig[i]==1 & rsb[i]==0 & psb[i-1]==0)                   {.8}
             else if ((trig[i]==1 & rsb[i]==1) || (trig[i]==1 & psb[i-1]==1)) {.1}
             else                                                             {0}
  p11.bel <- if      (trig[i]==0)                                             {.8}#
             else if (trig[i]==1 & rsb[i]==0 & psb[i-1]==0)                   {.2}
             else if ((trig[i]==1 & rsb[i]==1) || (trig[i]==1 & psb[i-1]==1)) {.1}
             else                                                             {.1}
  p12.bel <- 1 - (p10.bel+p11.bel)
  p13.bel <- 0
  p20.bel <- 0
  p21.bel <- if      (trig[i]==0)                                             {.1}#
             else if (trig[i]==1 & rsb[i]==0 & psb[i-1]==0)                   {.9}
             else if ((trig[i]==1 & rsb[i]==1) || (trig[i]==1 & psb[i-1]==1)) {.1}
             else                                                             {0}
  p22.bel <- if      (trig[i]==0)                                             {.85}#
             else if (trig[i]==1 & rsb[i]==0 & psb[i-1]==0)                   {.1}
             else if ((trig[i]==1 & rsb[i]==1) || (trig[i]==1 & psb[i-1]==1)) {.3}
             else                                                             {.2}
  p23.bel <- 1 - (p21.bel+p22.bel)
  p30.bel <- 0
  p31.bel <- 0
  p32.bel <- if      (trig[i]==0)                                             {.1}#
             else if (trig[i]==1 & rsb[i]==0 & psb[i-1]==0)                   {.95}
             else if ((trig[i]==1 & rsb[i]==1) || (trig[i]==1 & psb[i-1]==1)) {.1}
             else                                                             {0}
  p33.bel <- 1 - (p30.bel+p32.bel)  
  trans.bel <- matrix(c(p00.bel, p01.bel, p02.bel, p03.bel,
                        p10.bel, p11.bel, p12.bel, p13.bel,
                        p20.bel, p21.bel, p22.bel, p23.bel,
                        p30.bel, p31.bel, p32.bel, p33.bel),
                      byrow = T, nrow = 4)
  bel[i] <- if (bel[i-1]==0) {
              sample(c(0, 1, 2, 3), 1, prob=c(p00.bel,p01.bel,p02.bel,p03.bel))}
            else if (bel[i-1]==1) {
              sample(c(0, 1, 2, 3), 1, prob=c(p10.bel,p11.bel,p12.bel,p13.bel))}
            else if (bel[i-1]==2) {
              sample(c(0, 1, 2, 3), 1, prob=c(p20.bel,p21.bel,p22.bel,p23.bel))}
            else {
              sample(c(0, 1, 2, 3), 1, prob=c(p30.bel,p31.bel,p32.bel,p33.bel))}
  # transition matrix of preventive safety behaviour (PSB)
  p01.psb <- par2*bel[i]^2
  p00.psb <- 1-p01.psb
  p11.psb <- (par2+.01)*bel[i]^2
  p10.psb <- 1-p11.psb
  trans.psb <- matrix(c(p00.psb, p01.psb,
                        p10.psb, p11.psb), byrow=T, nrow=2)
  psb[i] <- ifelse(psb[i-1] == 0,
               rbinom(1,1,prob=trans.psb[1,2]),
               rbinom(1,1,prob=trans.psb[2,2]))
    # if therapeutic intervention is simulated, uncomment the following code and comment out the previous 3 lines
  #psb[i] <-ifelse(i >= 15, 0, ifelse(psb[i-1] == 0,
              #rbinom(1,1,prob=trans.psb[1,2]),
              #rbinom(1,1,prob=trans.psb[2,2])))
  }
  # store all values in an object in long format
  ppl.long[j:(j+tpoints-1), 1] <- which(sequ==j)
  ppl.long[j:(j+tpoints-1), 2] <- trig
  ppl.long[j:(j+tpoints-1), 3] <- anx
  ppl.long[j:(j+tpoints-1), 4] <- rsb
  ppl.long[j:(j+tpoints-1), 5] <- bel
  ppl.long[j:(j+tpoints-1), 6] <- psb
  ppl.long[j:(j+tpoints-1), 7] <- rep(par1, tpoints)
  ppl.long[j:(j+tpoints-1), 8] <- rep(par2, tpoints)
}
```

### Model 2 - the latent disease model

Starting values

```{r Starting Values Model 2}
# set number of timepoints 
# each timepoint represents one day
tpoints2 <- 360

# storing space and starting value for the binary variable "trigger"
trig2 <- rep(NA, tpoints2) 
trig2[1] <- 0

# storing space and starting value for the categorical (0-3) variable "anxiety"
anx2 <- rep(NA, tpoints2) 
anx2[1] <- 0

# storing space and starting value for the binary variable "RSB"
rsb2 <- rep(NA, tpoints2) 
rsb2[1] <- 0

# storing space and starting value for the categorical (0-3) variable "belief"
bel2 <- rep(NA, tpoints2) 
bel2[1] <- 0

# storing space and starting value for the binary variable "PSB"
psb2 <- rep(NA, tpoints2) 
psb2[1] <- 0

# storing space for N ppl
N2 <- 1000
ppl.long2 <- matrix(NA, nrow=tpoints2*N2, ncol=7)
colnames(ppl.long2) <- c("ID", "trig2", "anx2", "rsb2", "bel2", "psb2","lat2")

# storing space and starting value for the latent variable 
lat2 <- rep(NA, tpoints2)
lat2[1] <- 0
```

The model

```{r Data Generation Model 2}
# set seed for reproducibility
set.seed(123)
# set number of loops for outer for loop
sequ2 <- seq(from=1, to=(N2*tpoints2), by=tpoints2)

for (j in sequ2){

lat2 <-  rbeta(1, 1.3, 6) 
  
  for (i in 2:tpoints2){
    
     trig2[i] <- rbinom(1, 1, lat2)
     
     p0.anx2 <- ifelse(trig2[i]==0, 1, .4*(lat2-1)^2)
     p1.anx2 <- ifelse(trig2[i]==0, 0, -.5*(lat2-.3)^2+.4)
     p2.anx2 <- ifelse(trig2[i]==0, 0, -.5*(lat2-.7)^2+.4)
     p3.anx2 <- 1 - (p0.anx2+p1.anx2+p2.anx2)
    
     anx2[i] <- sample(c(0,1,2,3), 1, prob=c(p0.anx2, p1.anx2, p2.anx2, p3.anx2))
     
     rsb2[i] <- ifelse(trig2[i]==0, 0, rbinom(1, 1, lat2))
      # if therapeutic intervention is simulated, uncomment the following code and comment out the previous line
     #rsb2[i] <- ifelse(i>=360, 0, ifelse(trig2[i]==0, 0, rbinom(1, 1, lat2)))
     
     p0.bel2 <- .4*(lat2-1)^2
     p1.bel2 <- -.5*(lat2-.3)^2+.4
     p2.bel2 <- -.5*(lat2-.7)^2+.4
     p3.bel2 <- 1 - (p0.bel2+p1.bel2+p2.bel2)

     bel2[i] <- sample(c(0, 1, 2, 3), 1, prob=c(p0.bel2,p1.bel2,p2.bel2,p3.bel2))

     psb2[i] <-  rbinom(1, 1, lat2/5)
      # if therapeutic intervention is simulated, uncomment the following code and comment out the previous line
     #psb2[i] <-  ifelse(i>=360, 0, rbinom(1, 1, lat2/5))
  }
  # store all values in an object in long format
ppl.long2[j:(j+tpoints2-1), 1] <- which(sequ2==j)
ppl.long2[j:(j+tpoints2-1), 2] <- trig2
ppl.long2[j:(j+tpoints2-1), 3] <- anx2
ppl.long2[j:(j+tpoints2-1), 4] <- rsb2
ppl.long2[j:(j+tpoints2-1), 5] <- bel2
ppl.long2[j:(j+tpoints2-1), 6] <- psb2
ppl.long2[j:(j+tpoints2-1), 7] <- rep(lat2, tpoints2)
}
```


